export const LISTEN_TO_CURRENT_USER_PROFILE = 'LISTEN_TO_CURRENT_USER_PROFILE';
export const LISTEN_TO_SELECTED_USER_PROFILE =
  'LISTEN_TO_SELECTED_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const LOAD_CURRENT_USER_PROFILE = 'LOAD_CURRENT_USER_PROFILE';
